port of ScanningAndDetecting3DObjects
xamarin/monotouch-samples pull request #435
Opened 2022-01-14 16:54 UTC by stephen-hawley

This is a huge sample, thanks for your patience.

2022-01-17 14:07 UTC, rolfbjarne requested changes

2022-01-17 14:07 UTC, rolfbjarne commented on dotnet/ios/ios12/ScanningAndDetecting3DObjects/ScanningApp/3D_UI/ScannedObject.cs
> +				base.Dispose ();
The Dispose pattern is wrong, the `Dispose (bool)` method should call the same base method, so:

```
base.Dispose (disposing);
```

This effectively changes the whole method, and the comment in the README about Xamarin's weird Dispose pattern is also wrong (the original author got the Dispose pattern wrong).

This method would become:

```csharp
if (!disposed)
{
    disposed = true;
    NSNotificationCenter.DefaultCenter.RemoveObserver (notificationObserverHandle);
    Origin?.Dispose ();
    BoundingBox?.Dispose ();
    GhostBoundingBox?.Dispose ();
}
base.Dispose (disposing);
```

Ref: https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#implement-the-dispose-pattern-for-a-derived-class

This occurs in other files as well.

2022-01-18 14:19 UTC, stephen-hawley commented on dotnet/ios/ios12/ScanningAndDetecting3DObjects/ScanningApp/3D_UI/ScannedObject.cs
> +
I think I'm just going to remove these. They were sketchy anyway. At least one was marked as being put in for debugging.

2022-01-21 17:24 UTC, rolfbjarne approved these changes

2022-01-21 20:20 UTC, tj-devel709 commented on dotnet/ios/ios12/ScanningAndDetecting3DObjects/ScanningApp/3D_UI/ScannedObject.cs
> +		{
Not sure if worth going through many of these, but mono guidelines recommend `if () {` as well as the else statement

2022-01-21 20:20 UTC, tj-devel709 commented on dotnet/ios/ios12/ScanningAndDetecting3DObjects/ScanningApp/3D_UI/ScannedObject.cs
> +		var state = notification.UserInfo [Scan.StateUserInfoKey] as SimpleBox<Scan.ScanState>;
good place for is operator

2022-01-21 20:20 UTC, tj-devel709 commented on dotnet/ios/ios12/ScanningAndDetecting3DObjects/ScanningApp/3D_UI/ScannedPointCloud.cs
> +		var state = notification.UserInfo? [Scan.StateUserInfoKey] as SimpleBox<Scan.ScanState>;
is operator would be good here

2022-01-21 20:20 UTC, tj-devel709 commented on dotnet/ios/ios12/ScanningAndDetecting3DObjects/ScanningApp/3D_UI/Tile.cs
> +}
new line

2022-01-21 20:20 UTC, tj-devel709 commented on dotnet/ios/ios12/ScanningAndDetecting3DObjects/ScanningApp/Controllers/TestRun.cs
> +				if (sceneView.Session.Configuration as ARWorldTrackingConfiguration is not null)
```suggestion
				if (sceneView.Session.Configuration as ARWorldTrackingConfiguration)
```
Think this is redundant

2022-01-21 20:20 UTC, tj-devel709 commented on dotnet/ios/ios12/ScanningAndDetecting3DObjects/ScanningApp/Controllers/ViewControllerNavigationBar.cs
> +		navigationItem.LeftBarButtonItem = backButton;
Can these be added to the constructor?

2024-04-29 09:28 UTC, rolfbjarne commented
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs. In preparation for this, all issues and PRs in this repository are being closed.

2024-04-29 09:28 UTC, closed without merging