[Dotnet] XamarinShot port
xamarin/monotouch-samples pull request #436
Opened 2022-01-20 21:41 UTC by stephen-hawley

Yes, 531 files. Sorry, you gotta dance with them what brung ya

2022-01-21 17:25 UTC, rolfbjarne requested changes

2022-01-21 17:25 UTC, rolfbjarne commented on dotnet/ios/ios12/XamarinShot/XamarinShot/Utils/SimdExtensions.cs
> +                // only for column-major matrixes
Looks like this sample will have to be updated after the next preview (to pick up our SCNMatrix4 changes).

2022-01-21 17:25 UTC, rolfbjarne commented on dotnet/ios/ios12/XamarinShot/XamarinShot/Main.cs
> +            UIApplication.Main(args, null, "AppDelegate");
```suggestion
            UIApplication.Main(args, null, typeof (AppDelegate));
```

2022-01-21 19:33 UTC, stephen-hawley commented on dotnet/ios/ios12/XamarinShot/XamarinShot/XamarinShot.csproj
> +	<SceneKitAsset Include="art.scnassets\blocks\entities\block_archA.scn" />
Yes, yes I have. Without this, it doesn't run.

2022-01-21 21:27 UTC, tj-devel709 reviewed
I heard that the average American scrolls the height of the Statue of Liberty every day...
After this review, I feel like I have to at least be at 3 Statue of Liberty's ahah

2022-01-21 21:27 UTC, tj-devel709 commented on dotnet/ios/ios12/XamarinShot/XamarinShot/Core/Local Networking/NetworkSession.cs
> +                invitationHandler (true, Session);
Maybe this method should be capitalized

2022-01-21 21:27 UTC, tj-devel709 commented on dotnet/ios/ios12/XamarinShot/XamarinShot/Core/Local Networking/ProximityManager.cs
> +        readonly NSUuid RegionUUID = new NSUuid ("53FA6CD3-DFE4-493C-8795-56E71D2DAEAF");
```suggestion
        readonly NSUuid RegionUuid = new NSUuid ("53FA6CD3-DFE4-493C-8795-56E71D2DAEAF");
```

2022-01-21 21:27 UTC, tj-devel709 commented on dotnet/ios/ios12/XamarinShot/XamarinShot/Core/World Map Loading/KeyPositionAnchor.cs
> +                var other = anchor as KeyPositionAnchor;
good is operator use

2024-04-29 09:28 UTC, rolfbjarne commented
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs. In preparation for this, all issues and PRs in this repository are being closed.

2024-04-29 09:28 UTC, closed without merging